import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Sidebar from "./dashboard/components/Sidebar";

import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Task manager | Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={`w-full h-screen max-h-screen flex bg-[#F1F5F9]`}>
          <div className='w-[20%] hidden sm:block h-full'>
            <Sidebar />
          </div>
          <section className="w-full sm:w-[80%] h-full overflow-y-scroll">
            {children}
          </section>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
